services:
  app:
    image: emanager:latest
    container_name: emanager
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    env_file: .env
    environment:
      - NODE_ENV=production
    ports:
      - ${PORT}:${PORT}
    volumes:
      - "./logs:/app/logs"
